name: 'Forrest Artifact Upload'
description: 'Upload artifacts to the local Forrest runner'
author: 'Leonard Göhrs'

branding:
  icon: 'upload'
  color: 'green'

inputs:
  name:
    description: 'Upload destination as configured in the Forrest runner'
    default: 'artifact'

  path:
    description:
      'A file, directory or wildcard pattern that describes what to upload'
    required: true

  include-hidden-files:
    description: >
      If true, hidden files will be included in the artifact. If false, hidden
      files will be excluded from the artifact.
    default: 'false'

  token:
    description: 'The token used to authenticate this upload'
    default: ''

outputs:
  artifact-url:
    description: >
      The URL prefix under which the artifacts were just uploaded. To retrieve a
      specific file the respective file name as to be appended.

runs:
  using: node20
  main: dist/index.js
